apt_packages:
  - ntp
  - tree
  - psmisc
  - htop
  - mysql-client
  - telnet
  - silversearcher-ag
  - jq
  - dstat
  - bc
  - git

config_files:

  - src: htop
    dir: '~/.config'

  - src: ackrc
    dest: '.ackrc'

  - src: gitconfig
    dest: '.gitconfig'

  - src: gitignore_global
    dest: '.gitignore_global'