apt_packages:
  - ntp
  - tree
  - psmisc
  - htop
  - mysql-client
  - telnet
  - silversearcher-ag
  - jq
  - dstat
  - bc
  - git
  - gcc
  - make

brew_packages:
  - jq
  - vim
  - the_silver_searcher
  - tree
  - wget
  - htop-osx
  - gpg
  - mysql-client
  - automake
  - autoconf
  - kubernetes-cli
  - awscli
# src: required
# dest: default is { src }
# dest_dir: default is "{{ ansible_env.HOME }}" or the user's home directory

config_files:

  - src: htop
    dest_dir: '{{ ansible_env.HOME }}/.config'

  - src: ackrc
    dest: '.ackrc'

  - src: gitconfig
    dest: '.gitconfig'

  - src: gitignore_global
    dest: '.gitignore_global'

  - src: inputrc
    dest: '.inputrc'

  - src: screenrc
    dest: '.screenrc'
