---
- name: Install VIM
  apt: name=vim state=latest

- name: Copy vim configurations
  file:
    src: '~/.personal/vim/files'
    dest: '~/.vim'
    state: link

- name: Clone vundle repo
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: no

- name: Install vundle plugins
  shell: vim +PluginInstall +qall

