---
- name: Install VIM via apt
  apt: name=vim state=latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install VIM via homebrew
  homebrew:
    name: vim
    state: latest
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'

- name: Copy vim configurations
  file:
    src: '{{ ansible_env.HOME }}/.personal/vim/files'
    dest: '{{ ansible_env.HOME }}/.vim'
    state: link
    force: yes

- name: Clone vundle repo
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: '{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim'
    update: no

- name: Install vundle plugins
  shell: vim +PluginInstall +qall
  async: 120
  poll: 0