---
- name: Install VIM
  apt: name=vim state=latest

- name: Copy vim configurations
  file:
    src: '{{ ansible_env.HOME }}/.personal/vim/files'
    dest: '{{ ansible_env.HOME }}/.vim'
    state: link

- name: Clone vundle repo
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: '{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim'
    update: no

- name: Install vundle plugins
  shell: vim +PluginInstall +qall
  async: 120
  poll: 0