- name: Remove default tmux version
  apt:
    name: tmux
    state: absent
    purge: yes
  become: yes

- name: Install dependencies
  apt: name='{{ item }}' state=latest update_cache=true
  with_items:
    - autotools-dev
    - automake
    - libevent-dev
    - ncurses-dev
    - gcc
    - make
  become: yes

- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: tmux
  register: tmp_dir_obj

- name: Get the path of the tmpdir
  set_fact:
    tmpdir: '{{ tmp_dir_obj.path }}'

- name: Extract Tmux Sources
  unarchive:
    src: '{{tmux_tgz_url}}'
    dest: '{{ tmpdir }}'
    remote_src: yes

- name: configure, make, install
  shell: '{{ item }}'
  args:
    chdir: '{{ tmpdir }}/tmux-2.6'
  with_items:
    - ./configure
    - make
    - make install
  become: yes

