---
# remove undesirable tmux version
# install tmux if absent
# install tpm for the user
# install config files for the user

- name: Check if tmux exists
  stat:
    path: /usr/local/bin/tmux
  register: tmux

- include_tasks: install_tmux.yml
  when: tmux.stat.islnk is not defined

- name: Copy tmux config
  file:
    src: '~/.personal/tmux/files/tmux.conf'
    dest: '~/.tmux.conf'
    state: link

- include_tasks: install_tpm.yml