---
# remove undesirable tmux version
# install tmux if absent
# install tpm for the user
# install config files for the user

- name: Check if tmux exists
  stat:
    path: /usr/local/bin/tmux
  register: tmux_stats

- include_tasks: install_tmux_ubuntu.yml
  when: tmux_stats.stat.islnk is not defined and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')


- name: Install tmux via homebrew
  homebrew:
    name:
      - tmux
      - reattach-to-user-namespace
    state: latest
    update_homebrew: yes
  when: ansible_distribution == 'MacOSX'

- name: Copy tmux config
  file:
    src: '{{ ansible_env.HOME }}/.personal/tmux/files/tmux.conf'
    dest: '{{ ansible_env.HOME }}/.tmux.conf'
    state: link

- include_tasks: install_tpm.yml