---
- name: 'install packages'
  apt: name="{{ item }}" state=latest update_cache=true
  with_items: '{{ apt_packages }}'
  become: yes

- name: 'Debug'
  debug: msg='{{ item }}'
  with_items: '{{ config_files }}'

- name: 'Create configuration directory structure'
  file:
    dest: '{{ item.dir | default("~") }}'
    state: directory
    recurse: yes
  with_items: '{{ config_files }}'

- name: 'Symlink the configuration files'
  file:
    src: '{{ role_path }}/files/{{ item.src }}'
    dest: '{{ item.dir | default("~") }}/{{ item.dest | default(item.src) }}'
    state: link
  with_items: '{{ config_files }}'