" To install vundle plugins
" git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
" vim +PluginInstall +qall

set shell=/bin/bash
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" Sends commands to a tmux pane
Plugin 'jpalardy/vim-slime'
" Parenthesis Syntax
Plugin 'kien/rainbow_parentheses.vim'
" GoLang
Plugin 'fatih/vim-go'
" Fish
Plugin 'dag/vim-fish'
" Stores current session
Plugin 'tpope/vim-obsession'
" Markdown plugins
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'

Bundle 'wakatime/vim-wakatime'

" All of your Plugins must be added before the following line
call vundle#end()            " required
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line
"
set number
set relativenumber
set pastetoggle=<F3>

" Look and feel {{{
syntax on
set background=light
" colorscheme solarized

filetype indent plugin on
set tabstop=4 softtabstop=4 expandtab shiftwidth=4 smarttab

" Remap esc to tab
" nnoremap <Tab> <Esc>
" vnoremap <Tab> <Esc>gV
" onoremap <Tab> <Esc>
" cnoremap <Tab> <C-C><Esc>
" inoremap <Tab> <Esc>`^
" inoremap <Leader><Tab> <Tab>

" Execute the current file in bash. Shortcut key is <F1>
map <F1> <Esc> :w<CR> :!./%<CR>

" Remap esc to jk
inoremap jk <ESC>

" Clojure options.
let g:slime_target = "tmux"

autocmd Syntax clojure RainbowParenthesesLoadRound
autocmd BufEnter *.clj RainbowParenthesesToggle
autocmd BufLeave *.clj RainbowParenthesesToggle

let g:rbpt_colorpairs = [
    \ ['magenta',     'purple1'],
    \ ['cyan',        'magenta1'],
    \ ['green',       'slateblue1'],
    \ ['yellow',      'cyan1'],
    \ ['red',         'springgreen1'],
    \ ['magenta',     'green1'],
    \ ['cyan',        'greenyellow'],
    \ ['green',       'yellow1'],
    \ ['yellow',      'orange1'],
    \ ]
let g:rbpt_max = 9

" Functions
