# https://launchpad.net/~fish-shell/+archive/ubuntu/release-2
- name: Subscribe to fish channel
  apt_repository:
    repo: 'ppa:fish-shell/release-2'
  become: yes

- name: Install Fish
  apt:
    name: fish
    update_cache: yes
    state: latest
  become: yes