- name: Download omf
  get_url:
    url: https://get.oh-my.fish
    dest: /tmp/omf_install
    mode: 0700

- name: Install omf for '{{ user }}'
  shell: /tmp/omf_install --noninteractive --verbose -y
  args:
    creates: '{{ ansible_env.HOME }}/.config/omf/'

- name: Install omf packages
  shell: 'source {{ ansible_env.HOME }}/.config/fish/conf.d/omf.fish; omf install {{ item }}'
  with_items:
    - z
    - foreign-env
    - nvm
    - rvm
  args:
    executable: fish
