- name: Download omf
  get_url:
    url: https://get.oh-my.fish
    dest: /tmp/omf_install
    mode: 0700
  become_user: '{{ user }}'


- name: Install omf for '{{ user }}'
  shell: /tmp/omf_install --noninteractive --verbose -y
  become_user: '{{ user }}'
