# https://launchpad.net/~fish-shell/+archive/ubuntu/release-2
- name: Subscribe to fish channel
  apt_repository:
    repo: 'ppa:fish-shell/release-3'
    state: present
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install Fish
  apt:
    name: fish
    update_cache: yes
    state: latest
  become: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'